name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4.5.0
      with:
        distribution: 'zulu'
        java-version: 11
    - name: run lint and unitTest
      run: ./gradlew lintDebug testDebugUnitTest
    - name: run instrumented tests
      uses: reactivecircus/android-emulator-runner@v2.25.0
      with:
        api-level: 31
        arch: x86_64
        script: ./gradlew connectedCheck
